#message body examlple: {"EventsMetadata":{"CorrelationId":"myidaw"},"heyvalue":"testy!"}

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sqs-sensor
  labels:
    # sensor controller with instanceId "argo-events" will process this sensor
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    # sensor controller will use this label to match with it's own version
    # do not remove
    argo-events-sensor-version: v0.11
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor:v0.11"
          imagePullPolicy: IfNotPresent 
      serviceAccountName: argo-events-sa
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  dependencies:
    - name: "aws-sqs-gateway:bchase-eventstatepoc"
  triggers:
    - template:
        name: webhook-pod-trigger
        group: ""
        version: v1
        resource: pods
        source:
          inline: |
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: hello-world-
            spec:
              restartPolicy: Never
              containers:
                - name: hello-container
                  args:
                    - "-c"
                    - "echo helloworld && sleep 20"
                  command:
                    - "sh"
                  image: "amouat/network-utils"
      resourceParameters:
        - src:
            event: "aws-sqs-gateway:bchase-eventstatepoc"
            path: customargs
          dest: spec.containers.0.args.1
        - src:
            event: "aws-sqs-gateway:bchase-eventstatepoc"
            path: EventsMetadata.CorrelationId
          dest: metadata.labels.events/correlationId